const lineChartDefaultConfig = {
  isSync: true,
  showObs: false,
  showMeans: true,
  showOverallMean: true,
  showStds: false,
  showCIs: false,
  showLmmFit: false,
  showLmmCI: false,
  showComplete: true,
  showIncomplete: false,
  incompleteRequiredTimes: [],
  showLegend: true,
  showGrid: true,
  showGridBehindAll: false,
  lmmReferenceGroup: "All",
  lmmCovariates: [],
  lmmIncludeInteraction: false,
  lmmTimeCoding: "ordered-index",
  meanPointSize: 8,
  meanAsBoxplot: false,
  subjectPointSize: 3,
  meanStrokeWidth: 5,
  subjectStrokeWidth: 1,
  testIds: ["lmm-random-intercept"],
  testTimeFrom: null,
  testTimeTo: null,
  axisLabelFontSize: 16,
  yAxisMode: "auto",
  yAxisMin: null,
  yAxisMax: null,
};

export default lineChartDefaultConfig;
