export const theme = {
  token: {
    colorPrimary: "#0f172a",
    colorInfo: "#1e70c2",
    colorSuccess: "#16a34a",
    colorWarning: "#d97706",
    colorError: "#dc2626",
    colorText: "#0f172a",
    colorTextSecondary: "#334155",
    colorTextTertiary: "#64748b",
    colorBgLayout: "#f5f7fb",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBorder: "#e2e8f0",
    colorBorderSecondary: "#e2e8f0",
    fontFamily:
      'Manrope, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    fontSize: 16,
    fontSizeSM: 14,
    fontSizeLG: 18,
    fontSizeHeading1: 32,
    fontSizeHeading2: 28,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    lineHeight: 1.5,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.2,
    lineHeightHeading3: 1.2,
    lineHeightHeading4: 1.25,
    fontWeightStrong: 600,
    borderRadius: 10,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    boxShadow: "0 4px 10px rgba(15, 23, 42, 0.08)",
    boxShadowSecondary: "0 1px 2px rgba(15, 23, 42, 0.08)",
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 48,
  },
  components: {
    Slider: {
      handleColor: "#0f172a",
      railBg: "#e2e8f0",
    },
    Button: {
      defaultBg: "#1e70c2",
      defaultColor: "#fff",
      defaultBorderColor: "#1e70c2",
      defaultHoverBg: "#195fa8",
      defaultHoverColor: "#fff",
      defaultHoverBorderColor: "#195fa8",
      defaultActiveBg: "#144f8c",
      defaultActiveBorderColor: "#144f8c",
      fontWeight: 600,
    },
    Input: {
      activeBorderColor: "#1e70c2",
      hoverBorderColor: "#cbd5e1",
      activeShadow: "0 0 0 3px rgba(30, 112, 194, 0.25)",
    },
    Select: {
      optionSelectedBg: "rgba(30, 112, 194, 0.16)",
      optionActiveBg: "rgba(30, 112, 194, 0.12)",
      selectorBg: "#ffffff",
    },
    Card: {
      headerBg: "#ffffff",
    },
    Table: {
      headerBg: "#f8fafc",
      rowHoverBg: "rgba(30, 112, 194, 0.12)",
      borderColor: "#e2e8f0",
    },
    Modal: {
      contentBg: "#ffffff",
      headerBg: "#ffffff",
    },
    Tag: {
      defaultBg: "#f8fafc",
      defaultColor: "#334155",
    },
    Tooltip: {
      colorBgSpotlight: "#ffffff",
      colorTextLightSolid: "#0f172a",
    },
    Popover: {
      colorBgElevated: "#ffffff",
      colorText: "#0f172a",
    },
    Radio: {
      buttonBg: "transparent",
      buttonColor: "#334155",
      buttonBorderColor: "#e2e8f0",
      buttonHoverColor: "#0f172a",
      buttonHoverBorderColor: "#0f172a",
      buttonCheckedBg: "#0f172a",
      buttonCheckedColor: "#ffffff",
      buttonCheckedBorderColor: "#0f172a",
      buttonSolidCheckedBg: "#0f172a",
      buttonSolidCheckedColor: "#ffffff",
      buttonSolidCheckedHoverBg: "#0f172a",
      buttonSolidCheckedHoverColor: "#ffffff",
    },
  },
};
