export const theme = {
  token: {
    colorPrimary: "#4E6698",
    colorPrimaryBg: "#E6E8F1",
    colorPrimaryBgHover: "#DCE0EC",
    colorPrimaryBorder: "#C2CCE0",
    colorInfo: "#4E6698",
    colorSuccess: "#26A88E",
    colorWarning: "#B07A2A",
    colorError: "#B2545A",
    colorText: "#25324A",
    colorTextSecondary: "#4C5D7E",
    colorTextTertiary: "#7483A3",
    colorBgLayout: "#F3F5FB",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBorder: "#D6DDEA",
    colorBorderSecondary: "#D6DDEA",
    fontFamily:
      'Manrope, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    fontSize: 16,
    fontSizeSM: 14,
    fontSizeLG: 18,
    fontSizeHeading1: 32,
    fontSizeHeading2: 28,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    lineHeight: 1.5,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.2,
    lineHeightHeading3: 1.2,
    lineHeightHeading4: 1.25,
    fontWeightStrong: 600,
    borderRadius: 10,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    boxShadow: "0 4px 12px rgba(37, 50, 74, 0.14)",
    boxShadowSecondary: "0 1px 3px rgba(37, 50, 74, 0.12)",
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 48,
  },
  components: {
    Slider: {
      handleColor: "#4E6698",
      railBg: "#D6DDEA",
    },
    Button: {
      defaultBg: "#4E6698",
      defaultColor: "#fff",
      defaultBorderColor: "#4E6698",
      defaultHoverBg: "#435985",
      defaultHoverColor: "#fff",
      defaultHoverBorderColor: "#435985",
      defaultActiveBg: "#374A73",
      defaultActiveBorderColor: "#374A73",
      fontWeight: 600,
    },
    Input: {
      activeBorderColor: "#4E6698",
      hoverBorderColor: "#BCC8DE",
      activeShadow: "0 0 0 3px rgba(78, 102, 152, 0.25)",
    },
    Select: {
      optionSelectedBg: "rgba(78, 102, 152, 0.16)",
      optionActiveBg: "rgba(78, 102, 152, 0.12)",
      selectorBg: "#ffffff",
    },
    Card: {
      headerBg: "#ffffff",
    },
    Table: {
      headerBg: "#F7F8FC",
      rowHoverBg: "rgba(78, 102, 152, 0.12)",
      borderColor: "#D6DDEA",
    },
    Modal: {
      contentBg: "#ffffff",
      headerBg: "#ffffff",
    },
    Tag: {
      defaultBg: "#F7F8FC",
      defaultColor: "#4C5D7E",
    },
    Tooltip: {
      colorBgSpotlight: "#ffffff",
      colorTextLightSolid: "#25324A",
    },
    Popover: {
      colorBgElevated: "#ffffff",
      colorText: "#25324A",
    },
    Radio: {
      buttonBg: "transparent",
      buttonColor: "#4C5D7E",
      buttonBorderColor: "#D6DDEA",
      buttonHoverColor: "#25324A",
      buttonHoverBorderColor: "#4E6698",
      buttonCheckedBg: "#4E6698",
      buttonCheckedColor: "#ffffff",
      buttonCheckedBorderColor: "#4E6698",
      buttonSolidCheckedBg: "#4E6698",
      buttonSolidCheckedColor: "#ffffff",
      buttonSolidCheckedHoverBg: "#435985",
      buttonSolidCheckedHoverColor: "#ffffff",
    },
  },
};
