import { UI_COLORS } from "@/styles/uiColors";

const STATIC_TOKENS = {
  colorSuccess: UI_COLORS.success,
  colorWarning: UI_COLORS.warning,
  colorError: UI_COLORS.error,
  colorText: UI_COLORS.ink,
  colorTextSecondary: UI_COLORS.inkSecondary,
  colorTextTertiary: UI_COLORS.inkTertiary,
  colorBgLayout: UI_COLORS.background,
  colorBgContainer: UI_COLORS.surface,
  colorBgElevated: UI_COLORS.surface,
  colorBorder: UI_COLORS.border,
  colorBorderSecondary: UI_COLORS.border,
  fontFamily:
    'Manrope, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
  fontSize: 16,
  fontSizeSM: 14,
  fontSizeLG: 18,
  fontSizeHeading1: 32,
  fontSizeHeading2: 28,
  fontSizeHeading3: 24,
  fontSizeHeading4: 20,
  lineHeight: 1.5,
  lineHeightHeading1: 1.2,
  lineHeightHeading2: 1.2,
  lineHeightHeading3: 1.2,
  lineHeightHeading4: 1.25,
  fontWeightStrong: 600,
  borderRadius: 10,
  borderRadiusSM: 8,
  borderRadiusLG: 14,
  boxShadow: UI_COLORS.shadowSm,
  boxShadowSecondary: UI_COLORS.shadowXs,
  controlHeight: 40,
  controlHeightSM: 32,
  controlHeightLG: 48,
};

const createTheme = () => ({
  token: {
    ...STATIC_TOKENS,
    colorPrimary: UI_COLORS.brand,
    colorPrimaryBg: UI_COLORS.brandSoft,
    colorPrimaryBgHover: UI_COLORS.brandSoftSubtle,
    colorPrimaryBorder: UI_COLORS.brandBorder,
    colorInfo: UI_COLORS.brand,
    colorLink: UI_COLORS.brand,
  },
  components: {
    Slider: {
      handleColor: UI_COLORS.accent,
      trackBg: UI_COLORS.accent,
      trackHoverBg: UI_COLORS.accentHover,
      railBg: UI_COLORS.border,
    },
    Switch: {
      colorPrimary: UI_COLORS.accent,
      colorPrimaryHover: UI_COLORS.accentHover,
    },
    Checkbox: {
      colorPrimary: UI_COLORS.accent,
      colorPrimaryHover: UI_COLORS.accentHover,
    },
    Button: {
      defaultBg: UI_COLORS.surface,
      defaultColor: UI_COLORS.brand,
      defaultBorderColor: UI_COLORS.brand,
      defaultHoverBg: UI_COLORS.accent,
      defaultHoverColor: UI_COLORS.onBrand,
      defaultHoverBorderColor: UI_COLORS.accent,
      defaultActiveBg: UI_COLORS.accentActive,
      defaultActiveColor: UI_COLORS.onBrand,
      defaultActiveBorderColor: UI_COLORS.accentActive,
      colorPrimary: UI_COLORS.surface,
      colorPrimaryHover: UI_COLORS.accent,
      colorPrimaryActive: UI_COLORS.accentActive,
      primaryColor: UI_COLORS.brand,
      fontWeight: 600,
    },
    Input: {
      activeBorderColor: UI_COLORS.brand,
      hoverBorderColor: UI_COLORS.accentBorder,
      activeShadow: UI_COLORS.focusRing,
    },
    Select: {
      optionSelectedBg: UI_COLORS.accentSoft,
      optionActiveBg: UI_COLORS.accentSoftSubtle,
      selectorBg: UI_COLORS.surface,
    },
    Card: {
      headerBg: UI_COLORS.surface,
    },
    Table: {
      headerBg: UI_COLORS.surfaceMuted,
      rowHoverBg: UI_COLORS.accentSoftSubtle,
      borderColor: UI_COLORS.border,
    },
    Modal: {
      contentBg: UI_COLORS.surface,
      headerBg: UI_COLORS.surface,
    },
    Tabs: {
      inkBarColor: UI_COLORS.accent,
      itemSelectedColor: UI_COLORS.brand,
      itemHoverColor: UI_COLORS.accentActive,
    },
    Tag: {
      defaultBg: UI_COLORS.surfaceMuted,
      defaultColor: UI_COLORS.inkSecondary,
    },
    Tooltip: {
      colorBgSpotlight: UI_COLORS.surface,
      colorTextLightSolid: UI_COLORS.ink,
    },
    Popover: {
      colorBgElevated: UI_COLORS.surface,
      colorText: UI_COLORS.ink,
    },
    Radio: {
      buttonBg: UI_COLORS.surface,
      buttonColor: UI_COLORS.brand,
      buttonBorderColor: UI_COLORS.brand,
      buttonHoverColor: UI_COLORS.onBrand,
      buttonHoverBorderColor: UI_COLORS.accent,
      buttonCheckedBg: UI_COLORS.accentActive,
      buttonCheckedColor: UI_COLORS.onBrand,
      buttonCheckedBorderColor: UI_COLORS.accentActive,
      buttonSolidCheckedBg: UI_COLORS.accentActive,
      buttonSolidCheckedColor: UI_COLORS.onBrand,
      buttonSolidCheckedHoverBg: UI_COLORS.accentActive,
      buttonSolidCheckedHoverColor: UI_COLORS.onBrand,
    },
  },
});

export const theme = createTheme();
